# Generated by Django 5.1 on 2025-03-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('Clinical Laboratory Test', 'Clinical Laboratory Test'), ('Vision Health Check', 'Vision Health Check'), ('Dermatological Skin Exam', 'Dermatological Skin Exam')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
