# Generated by Django 5.1 on 2025-03-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Oncology', 'Oncology')], max_length=50)),
                ('hospital', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='doctors/')),
                ('available_days', models.CharField(max_length=100)),
                ('available_time', models.CharField(max_length=100)),
            ],
        ),
    ]
